links:
  - url: https://github.com/honai
    text: github.com/honai
    icon: github
  - url: https://twitter.com/_honai
    text: twitter.com/_honai
    icon: twitter
  - url: https://www.facebook.com/honai.ueoka/
    text: facebook.com/honai.ueoka
    icon: facebook
  - url: https://www.linkedin.com/in/honai-ueoka/
    text: linkedin.com/in/honai-ueoka
    icon: linkedin

education:
  - period: 2021.4 - 2023.3
    title: 京都大学大学院 情報学研究科 通信情報システム専攻 大木研究室（知的通信網分野）
  - period: 2020.4 - 2021.3
    title: 京都大学 工学部 電気電子工学科 黒橋研究室（言語メディア分野）
  - period: 2017.4 - 2021.3
    title: 京都大学 工学部 電気電子工学科

jobs:
  - period: 2020.8 - 2023.3
    title: エニシア株式会社（アルバイト）
  - period: 2021.3 - 2022.12
    title: ピクシブ株式会社（アルバイト）
  - period: "2021.9"
    title: サイボウズ株式会社（インターン, 1 week）
  - period: "2021.8"
    title: ヤフー株式会社（インターン, 2 weeks）
  - period: "2020.3"
    title: ピクシブ株式会社（インターン, 1 week）
  - period: "2019.8"
    title: 株式会社サイバーエージェント（インターン, 3 weeks）

publications:
  - title: Crosstalk-Aware Backup Network Design against Probabilistic Link Failures in Multi-Core Fiber Optical Path Network
    authors: Honai Ueoka, Takehiro Sato and Eiji Oki.
    journal:
      2022 27th OptoElectronics and Communications Conference (OECC)
      and 2022 International Conference on Photonics in Switching and Computing (PSC).
    links:
      - text: paper
        url: https://ieeexplore.ieee.org/document/9850212
  - title: Frustratingly Easy Edit-based Linguistic Steganography with a Masked Language Model.
    authors: Honai Ueoka, Yugo Murawaki and Sadao Kurohashi.
    journal:
      "In Proceedings of the 2021 Conference of the North American Chapter of
      the Association for Computational Linguistics: Human Language Technologies (NAACL-HLT
      2021), pp. 5486-5492, online, June 2021. (short paper)."
    links:
      - text: paper
        url: https://www.aclweb.org/anthology/2021.naacl-main.433/
      - text: code
        url: https://github.com/ku-nlp/steganography-with-masked-lm
  - title: A System for Worldwide COVID-19 Information Aggregation.
    authors:
      Akiko Aizawa, Frederic Bergeron, Junjie Chen, Fei Cheng, Katsuhiko Hayashi,
      Kentaro Inui, Hiroyoshi Ito, Daisuke Kawahara, Masaru Kitsuregawa, Hirokazu Kiyomaru,
      Masaki Kobayashi, Takashi Kodama, Sadao Kurohashi, Qianying Liu, Masaki Matsubara,
      Yusuke Miyao, Atsuyuki Morishima, Yugo Murawaki, Kazumasa Omura, Haiyue Song,
      Eiichiro Sumita, Shinji Suzuki, Ribeka Tanaka, Yu Tanaka, Masashi Toyoda, Nobuhiro
      Ueda, Honai Ueoka, Masao Utiyama, Ying Zhong.
    journal:
      Workshop on NLP for COVID-19 (Part 2) at EMNLP 2020, online, November 2020.
      (workshop)
    links:
      - text: paper
        url: https://www.aclweb.org/anthology/2020.nlpcovid19-2.13/

works:
  - name: CAMPHOR- Website
    url: https://camph.net/
    thumb: https://res.cloudinary.com/honai/image/upload/f_auto/v1638781653/portfolio/camph-net.jpg
    desc: |
      * DjangoからNext.js + Goへのリプレイスを実施。
      * [CAMPHOR-のWebサイトをリプレイスした (フロントエンド編)](https://blog.camph.net/release/new-website-1/)
  - name: COVID-19 World Information Watcher
    url: https://lotus.kuee.kyoto-u.ac.jp/NLPforCOVID-19/
    thumb: /images/covid-19-watcher.png
    desc: |
      * Code (frontend): [NLPforCOVID-19 / covid-19-ui](https://github.com/NLPforCOVID-19/covid-19-ui)
      * [「世界中のCOVID-19情報が俯瞰できるサイトを構築」第89号 - NII Today](https://www.nii.ac.jp/today/89/2.html)
      * [Paper](https://www.aclweb.org/anthology/2020.nlpcovid19-2.13/)
  - name: ExcElm
    url: https://excelm.honai.me/
    thumb: /images/excelm.png
    desc: |
      * Code: [honai / excelm](https://github.com/honai/excelm)
      * [ElmでミニExcelを作ろう - Qiita](https://qiita.com/honai/items/061b024839f1d174436e)
  - name: 質問箱
    url: https://qa.honai.me/
    thumb: /images/neing.png
    desc: |
      * Code: private
      * TypeScript / Next.js / Firebase
  - name: VSCode Shortcuts Wallpaper
    url: https://honai.github.io/vscode-shortcuts-wallpaper/
    thumb: /images/vscode-shortcut.png
    desc: |
      * Code: [honai / vscode-shortcuts-wallpaper](https://github.com/honai/vscode-shortcuts-wallpaper)
      * Just reproduced the official keyboard shortcuts reference (PDF) with CSS with darker theme.

articles:
  - title: CAMPHOR- 2022年の総括 ～やりたいことに使ってもらえるコミュニティ～
    url: https://blog.camph.net/news/2022-advent-final/
    date: 2022-12-25
    source:
      title: CAMPHOR- Blog
      url: https://blog.camph.net/author/honai/
  - title: CAMPHOR-のWebサイトをリプレイスした (フロントエンド編)
    url: https://blog.camph.net/release/new-website-1/
    date: 2021-12-09
    source:
      title: CAMPHOR- Blog
      url: https://blog.camph.net/author/honai/
