on:
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      # deployments: write

    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy public --project-name=honai-me
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
