name: Generate slide images

on:
  push:
    paths:
      - "src/slides/*.pdf"

jobs:
  generate-slide-images:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - run: sudo apt install poppler-utils

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: false

      - run: gem install pdf-reader

      - uses: actions/checkout@v3

      - run: ruby pdf-convert.rb

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit & Push
        if: steps.diff.outcome == 'failure'
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'generate slide images'
          git push
