name: pnpm update

on:
  # schedule:
  #   - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    env:
      GA_EMAIL: github-actions[bot]@users.noreply.github.com
      BASE_BRANCH: main
      PR_BRANCH: pnpm-update

    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: git config
        run: |
          git config user.name github-actions[bot]
          git config user.email $GA_EMAIL

      - id: fetch
        run: |
          git fetch origin $PR_BRANCH
          git switch $PR_BRANCH
        continue-on-error: true

      - if: steps.fetch.outcome == 'failure'
        run: |
          git switch -c $PR_BRANCH

      - if: steps.fetch.outcome == 'success'
        # switched to existing branch
        # fail if author is not the bot
        run: |
          test `git show HEAD --quiet --format=%ae` = $GA_EMAIL
          git reset --hard $BASE_BRANCH

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: run pnpm update
        run: |
          corepack enable
          pnpm update

      - id: diff
        run: |
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit & Push
        if: steps.diff.outcome == 'failure'
        run: |
          git add .
          git commit -m 'pnpm update'
          git push --set-upstream --force origin $PR_BRANCH

      - name: PR
        if: steps.diff.outcome == 'failure'
        run: |
          gh pr view --json=number || gh pr create --fill --reviewer honai
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
